---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: hmda-data-browser-api
  type: ClusterIP
  ports:
  - name: {{ .Values.databrowser.name }}
    protocol: {{ .Values.databrowser.protocol }}
    port: {{ .Values.databrowser.port }}
    targetPort: {{ .Values.databrowser.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-hmda-data-browser-api
  name: ambassador-hmda-data-browser-api
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v2
      kind: Mapping
      name: hmda_databrowser_mapping
      {{- if .Values.ambassador_id }}
      ambassador_id: {{ .Values.ambassador_id }}
      {{- end}}
      {{- if .Values.ambassador_host }}
      host: {{ .Values.ambassador_host }}
      {{- end}}
      prefix: /v2/data-browser-api/
      service: {{ .Values.service.name }}:{{ .Values.databrowser.port }}
      timeout_ms: 3800000
      retry_policy:
        num_retries: 10
        retry_on: 5xx
      add_response_headers:
        referrer-policy: 
          value: strict-origin
          append: False
        content-security-policy: 
          append: False
          value: "default-src 'self' blob:; script-src 'self' 'unsafe-inline' blob: data: https://tagmanager.google.com https://www.googletagmanager.com https://www.google-analytics.com https://*.cfpb.gov https://www.consumerfinance.gov; img-src 'self' blob: data: https://www.google-analytics.com https://raw.githubusercontent.com; style-src 'self' 'unsafe-inline'; font-src 'self' data:; object-src 'none'; frame-src 'self' https://www.youtube.com/ https://ffiec.cfpb.gov/; connect-src 'self' https://*.cfpb.gov https://www.consumerfinance.gov https://raw.githubusercontent.com https://ffiec-api.cfpb.gov https://ffiec.cfpb.gov https://*.mapbox.com https://www.google-analytics.com https://s3.amazonaws.com"
        permissions-policy:
          value: "autoplay=(), encrypted-media=(), fullscreen=(), geolocation=(), microphone=(), midi=()"
        x-frame-Options: 
          value : "SAMEORIGIN"
        x-content-type-options: 
          value : nosniff
        strict-transport-security:
          value: "max-age=31536000; includeSubDomains; preload"
        x-xss-protection:
          value: "1; mode=block"
      remove_response_headers:
      - Access-Control-Allow-Origin
      - x-envoy-upstream-service-time
      - x-forwarded-host
      - x-host
      - x-forwarded-server        
      labels:
        ambassador:
         - string_request_label:
           - hmda-reporting
spec:
  clusterIP: None
