---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: hmda-data-browser-api
  type: ClusterIP
  ports:
  - name: {{ .Values.databrowser.name }}
    protocol: {{ .Values.databrowser.protocol }}
    port: {{ .Values.databrowser.port }}
    targetPort: {{ .Values.databrowser.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-hmda-data-browser-api
  name: ambassador-hmda-data-browser-api
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind: Mapping
      name: hmda_databrowser_mapping
      ambassador_id: ambassador-default-1
      prefix: /v2/data-browser-api/
      service: {{ .Values.service.name }}:{{ .Values.databrowser.port }}
      timeout_ms: 1800000
      rate_limits:
        - descriptor: hmda-reporting
spec:
  clusterIP: None  
  ports:
    - port: {{ .Values.databrowser.port }}
