---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "check-digit.fullname" . }}
  labels:
    app: {{ template "check-digit.name" . }}
    chart: {{ template "check-digit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "check-digit.name" . }}
    release: {{ .Release.Name }}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.ambassador.name }}
  name: {{ .Values.ambassador.name }}
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind: Mapping
      name: {{ .Values.ambassador.mapping }}
      prefix: {{ .Values.ambassador.prefix }}
      rewrite: {{ .Values.ambassador.service.prefix }}
      service: {{ template "check-digit.fullname" .}}:{{ .Values.service.port }}
spec:
  type: {{ .Values.ambassador.service.type }}
  ports:
  - name: {{ .Values.ambassador.name }}
    port: {{ .Values.ambassador.port }}
    targetPort: {{ .Values.ambassador.port }}
  selector:
    service: {{ .Values.ambassador.name }}