apiVersion: v1
kind: Service
metadata: 
  labels: 
    service: maildev-ambassador
  name: maildev-ambassador
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind: Mapping
      name: maildev_mapping
      prefix: /mail/
      rewrite: /
      service: maildev:80
spec:
  clusterIP: None
  ports:
    - ports: 80
