# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  # third cron
  - name: allclear-tests
    image:
      repository: dtr.cfpb.gov/hmda/newman-automation
      tag: latest
      imagePullPolicy: Always
    # optional env vars
    env:
      - name: HOST_FILING
        value:
      - name: HOST_ADMIN
        value:
      - name: HOST_PUBLIC
        value:
      - name: KC_UN
        value:
      - name: KC_PW
        value:
      - name: KC_URL
        value:
      - name: KC_CLIENT_ID
        value:
      - name: HMDA_ENV
        value:
      - name: MM_HOOK
        value:
      - name: NEWMAN_NOTIFY
        value: "daily"
    schedule: "30 17 * * *"
    command: ["/bin/bash"]
    args:
      -  "-c"
      - ./scripts/newmanFiling.sh $KC_UN $KC_PW $KC_URL $KC_CLIENT_ID $HOST_FILING $HOST_ADMIN $HOST_PUBLIC $HMDA_ENV $MM_HOOK $NEWMAN_NOTIFY
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
