apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: {{ include "hmda-quarterly-data-service.fullname" . }}_mapping
      {{- if .Values.ambassador_id }}
      ambassador_id: {{ .Values.ambassador_id }}
      {{- end}}
      {{- if .Values.ambassador_host }}
      host: {{ .Values.ambassador_host }}
      {{- end}}
      prefix: /quarterly-data/
      rewrite: /
      service: {{ include "hmda-quarterly-data-service.fullname" . }}:{{ .Values.service.port }}
      add_response_headers:
        referrer-policy: 
          value: strict-origin
          append: False
        content-security-policy: 
          append: False
          value: "default-src 'self' blob:; script-src 'self' 'unsafe-inline' blob: data: https://tagmanager.google.com https://www.googletagmanager.com https://www.google-analytics.com https://*.cfpb.gov https://www.consumerfinance.gov; img-src 'self' blob: data: https://www.google-analytics.com https://raw.githubusercontent.com; style-src 'self' 'unsafe-inline'; font-src 'self' data:; object-src 'none'; frame-src 'self' https://www.youtube.com/ https://ffiec.cfpb.gov/; connect-src 'self' https://*.cfpb.gov https://www.consumerfinance.gov https://raw.githubusercontent.com https://ffiec-api.cfpb.gov https://ffiec.cfpb.gov https://*.mapbox.com https://www.google-analytics.com https://s3.amazonaws.com"
        permissions-policy:
          value: "autoplay=(), encrypted-media=(), fullscreen=(), geolocation=(), microphone=(), midi=()"
        x-frame-Options: 
          value : "SAMEORIGIN"
        x-content-type-options: 
          value : nosniff
        strict-transport-security:
          value: "max-age=31536000; includeSubDomains; preload"
        x-xss-protection:
          value: "1; mode=block"
      remove_response_headers:
      - Access-Control-Allow-Origin
      - x-envoy-upstream-service-time
      - x-forwarded-host
      - x-host
      - x-forwarded-server      
  labels:
    {{- include "hmda-quarterly-data-service.labels" . | nindent 4 }}
  name: {{ include "hmda-quarterly-data-service.fullname" . }}-ambassador
spec:
  clusterIP: None
