---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap
data:
  cassandra-hosts: {{ .Values.cassandra.hosts }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
data:
  auth.url: {{ .Values.keycloak.url }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
data:
kafka.hosts: {{ .Values.kafka.hosts }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-configmap
data:
  check.digit.host: {{ .Values.grpc.check_digit.host }}
  check.digit.port: "{{ .Values.grpc.check_digit.port }}"
