apiVersion: v1
kind: Service
metadata: 
  labels: 
    service: keycloak-ambassador
  name: keycloak-ambassador
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: keycloak_https_mapping
      ambassador_id: ambassador-beta-2
      prefix: /auth/
      rewrite: /auth/
      service: keycloak-http.default.svc.cluster.local
      timeout_ms: 20000
spec:
  clusterIP : None
  ports:
  - name: keycloak-ambassador-beta
    port: 8443
    targetPort: 8443
  selector:
    app: keycloak
    release: keycloak
