---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-configmap
data:
  aws-environment: "{{ .Values.aws.environment }}"
  s3-private-bucket: "{{ .Values.aws.s3privatebucket }}"
  s3-public-bucket: "{{ .Values.aws.s3publicbucket }}"
  aws-region: "{{ .Values.aws.region }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modified-lar-http-configmap
data:
  census.host: {{ .Values.http.census.host }}
  census.port: "{{ .Values.http.census.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-filter-configmap
data:
  bank-filter-list: "{{ .Values.filter.bankfilterlist }}"