apiVersion: v1
kind: ConfigMap

metadata:
  name: hmda-data-publisher-dynamic-schedule-config
  annotations:

    reloader.stakater.com/match: "true"

data:
  COMBINED_MLAR_PUBLIC_SCHEDULE_CRON: 0 00 16 ? * SUN *
  COMBINED_MLAR_PUBLIC_SCHEDULE_YEARS: 2023,2024
  LAR_LOAN_LIMIT_SCHEDULE_CRON: 0 10 5 ? * MON *
  LAR_LOAN_LIMIT_SCHEDULE_YEARS: 2023,2024
  LAR_PUBLIC_SCHEDULE_CRON: 0 00 10 ? * SUN *
  LAR_PUBLIC_SCHEDULE_YEARS: 2023,2024
  LAR_QUARTERLY_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  LAR_QUARTERLY_SCHEDULE_YEARS: "2026"
  LAR_SCHEDULE_CRON: 0 00 14 ? * SUN *
  LAR_SCHEDULE_YEARS: 2023,2024
  PANEL_SCHEDULE_CRON: 0 10 8 ? * SUN *
  PANEL_SCHEDULE_YEARS: 2023,2024
  SPECIFIC_LAR_SCHEDULE_CRON: 0 20 5 * * ?
  SPECIFIC_LAR_SCHEDULE_YEARS: "2025"
  SPECIFIC_PANEL_SCHEDULE_CRON: 0 20 5 * * ?
  SPECIFIC_PANEL_SCHEDULE_YEARS: "2025"
  SPECIFIC_TS_SCHEDULE_CRON: 0 20 5 * * ?
  SPECIFIC_TS_SCHEDULE_YEARS: "2025"
  TS_PUBLIC_SCHEDULE_CRON: 0 00 8 ? * SUN *
  TS_PUBLIC_SCHEDULE_YEARS: 2023,2024
  TS_QUARTERLY_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  TS_QUARTERLY_SCHEDULE_YEARS: "2026"
  TS_SCHEDULE_CRON: 0 00 7 ? * SUN *
  TS_SCHEDULE_YEARS: 2023,2024
