apiVersion: v1
kind: ConfigMap
metadata:
  name: timed-guards
  annotations:
    reloader.stakater.com/match: "true"
data:
  yearsAllowed: "2023,2024,2025"
  currentYear: "2025"
  quarterlyYearsAllowed: "2026"
  q1Start: "April 01"
  q1End: "June 30"
  q2Start: "July 01"
  q2End: "September 30"
  q3Start: "October 01"
  q3End: "December 31"
  actionQ1Start: "January 01"
  actionQ1End: "March 31"
  actionQ2Start: "April 01"
  actionQ2End: "June 30"
  actionQ3Start: "July 01"
  actionQ3End: "September 31"
