apiVersion: v1
kind: ConfigMap
metadata:
  name: timed-guards
data:
  yearsAllowed: "2018,2019"
  currentYear: "2019"
  quarterlyYearsAllowed: "2020"
  q1Start: "April 01"
  q1End: "June 30"
  q2Start: "July 01"
  q2End: "September 30"
  q3Start: "October 01"
  q3End: "December 31"
