# Default values for check-digit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hmda/hmda-regulator
  tag: v2.7.2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9099
  targetPort: 9099
  name: http-regulator

grpc:
  type: ClusterIP
  port: 60082
  targetPort: 60082
  name: http2-regulator

ambassador:
  name: ambassador-regulator
  port: 80
  service:
    type: NodePort

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  ContainerPort: 9099
  hosts:
    - hmda-regulator.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: "4200Mi"
    cpu: "2"
  requests:
    memory: "4200Mi"
    cpu: "1"
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
aws:
  environment: prod
  s3privatebucket: cfpb-hmda-export
  s3publicbucket: cfpb-hmda-public
  region: us-east-1

filter:
    bankfilterlist: BANK1LEIFORTEST12345,BANK3LEIFORTEST12345,BANK4LEIFORTEST12345,999999LE3ZOZXUS7W648,28133080042813308004
