apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "file-proxy.fullname" . }}-publication-config
data:
  DYNAMIC_YEARS: 2017,2018,2019,2020,2021,2022,2023
  SNAPSHOT_YEARS: 2017,2018,2019,2020,2021,2022
  IRS_YEARS: 2017,2018,2019,2020,2021,2022,2023
