kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.service.account.name }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.service.account.name }}-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.service.account.name }}-binding
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: {{ .Values.service.account.name }} # "name" is case sensitive
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: {{ .Values.service.account.name }}-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
