---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-configmap
data:
  aws-environment: "{{ .Values.aws.environment }}"
  s3-private-bucket: "{{ .Values.aws.bucket }}"
  aws-region: "{{ .Values.aws.region }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-filter-configmap
data:
  bank-filter: "{{ .Values.filter.bankfilterlist }}"