apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: default
  labels:
    app: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  ambassador
      config:
        ambassador_id: ambassador-default-1  
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 30100
  selector:
    service: ambassador
